#!/bin/zsh

keyout()
{
        if [ "$name" = "root" ];
        then
                echo "echo \"$b64pkey\" | base64 -d > /$name/.ssh/authorized_keys && chmod 600 /home/$name/.ssh/authorized_keys"
        else
                echo "echo \"$b64pkey\" | base64 -d > /home/$name/.ssh/authorized_keys && chmod 600 /home/$name/.ssh/authorized_keys"
        fi
}

if [ -z "$1" ];
then
        echo "usage: htb-keygen username"
        exit 1
else
        name="$1"
        file="$1.id_rsa"

        if [ -z $(find ./ -type f -name $file 2>/dev/null) ] && [ -z $(find ./ -type f -name $file.pub 2>/dev/null) ];
        then
                b64pkey=$(ssh-keygen -q -t rsa -f "./$file" -N "" && cat $file.pub | cut -d' ' -f1,2 | base64 -w0)
                keyout
        else
                rm -f ./$file ./$file.pub
                b64pkey=$(ssh-keygen -q -t rsa -f "./$file" -N "" && cat $file.pub | cut -d' ' -f1,2 | base64 -w0)
                keyout
        fi
fi