#!/bin/zsh
keyout()
{
    ([[ "$name" = "root" ]] && userprofile="/root" ||)
    ([[ "$name" = "www-data" ]] && userprofile="/var/www" ||)
    userprofile="/home/$name";
   
    echo "mkdir -p ${userprofile}/.ssh/ && echo ${b64pkey} | base64 -d >> ${userprofile}/.ssh/authorized_keys && chmod 600 ${userprofile}/.ssh/authorized_keys"
}

if [ $# -le 1  ] || [[ "$2" != ("rsa"||"ed25519") ]];
then
    echo "usage: htb-keygen username rsa|ed25519"
    exit 1
else
    name="$1"
    algo="$2"
    file="$name.id_$algo"

    if [ -z $(find ./ -type f -name $file 2>/dev/null) ] && [ -z $(find ./ -type f -name $file.pub 2>/dev/null) ];
    then
        b64pkey=$(ssh-keygen -q -t $algo -f "./$file" -N "" -C "" && cat $file.pub | cut -d' ' -f1,2 | base64 -w0)
        keyout
    else
        rm -f ./$file ./$file.pub
        b64pkey=$(ssh-keygen -q -t $algo -f "./$file" -N "" -C "" && cat $file.pub | cut -d' ' -f1,2 | base64 -w0)
        keyout
    fi
fi
